### ISSUE TITLE
[Bug] Missing raise keyword when translation file is not found

### ISSUE THREAD

**Issue by gptgit** [KwiatekMiki/passnpingenerator#15] opened 2023-07-01 19:02 UTC
When the translation file for the user's Windows language is not found, the program prints a message but does not raise a `FileNotFoundError` exception. This can lead to incorrect behavior when the translations are missing.

**Steps to Reproduce:**
1. Run the program without the translation file for the user's Windows language.
2. Observe the program output.

**Expected Behavior:**
If the translation file for the user's Windows language is not found, the program should raise a `FileNotFoundError` exception.

**Actual Behavior:**
The program prints a message but does not raise an exception, resulting in missing translations and potentially incorrect program behavior.

**Additional Information:**
- Operating System: Windows 10
- Language: English
- Version: 1.0

**Comment by KwiatekMiki** [comment] 2023-07-03 19:56
Potential duplicate of #13
And it works fine.

**Closed as not planned by KwiatekMiki** 2023-07-03 19:57 UTC
Labels: duplicate, not true
